version: "3.0"

services:
    neo4j:
        restart: always
        image: neo4j:4.2.3
        container_name: neo4j
        ports:
            - "7474:7474"
            - "7687:7687"
        volumes:
            - ./export/neo4j/data:/data
#- ./export/neo4j/var/lib/neo4j/conf:/var/lib/neo4j/conf
            - ./export/neo4j/logs:/logs
#- ./export/neo4j/var/lib/neo4j/import:/var/lib/neo4j/import
            - ./export/neo4j/plugins:/plugins
        environment:
            - NEO4J_AUTH=neo4j/test

    api_backend:
        build:
            context: ./
        hostname: api_backend
        restart: always
        container_name: api_backend
        ports:
            - 3001:3001
        depends_on:
            - neo4j
    
    api_frontend:
        build:
            context: ../front
        hostname: api_frontend
        restart: always
        container_name: api_frontend
        ports:
            - 3000:3000
        depends_on:
            - api_backend
